// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { VITE_AUTH0_CLIENT_ID: "1cFscmFCBSd9mSliVUSCqi1EfQqJhHkt", VITE_AUTH0_DOMAIN: "dev-2uqchs17am41r5ed.us.auth0.com", VITE_SUPABASE_PROJECT_ID: "jhejjpqngvlttrdpgofr", VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWpqcHFuZ3ZsdHRyZHBnb2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODYxNDEsImV4cCI6MjA3MDY2MjE0MX0.G0lr22FeyMB2e2nYbLCYxluBzDbdW19sthdzjXw0ZoI", VITE_SUPABASE_URL: "https://jhejjpqngvlttrdpgofr.supabase.co", VITE_EMAILJS_SERVICE_ID: "service_hu9y3mh", VITE_EMAILJS_TEMPLATE_ID: "template_wza23sy", VITE_EMAILJS_PUBLIC_KEY: "YPx9GdffoRMZFJF2n", VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWpqcHFuZ3ZsdHRyZHBnb2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODYxNDEsImV4cCI6MjA3MDY2MjE0MX0.G0lr22FeyMB2e2nYbLCYxluBzDbdW19sthdzjXw0ZoI", MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.8";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-my-usage.ts
import { createClient } from "npm:@supabase/supabase-js@^2.55.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
async function resolveUserId(sub) {
  const admin = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
  const { data: ident } = await admin.from("external_identities").select("profile_id").eq("external_sub", sub).maybeSingle();
  if (!ident?.profile_id) return null;
  const { data: profile } = await admin.from("profiles").select("user_id").eq("id", ident.profile_id).maybeSingle();
  return profile?.user_id ?? null;
}
var get_my_usage_default = defineTool2({
  name: "get_my_usage",
  title: "Get my usage",
  description: "Return the signed-in user's current plan, monthly image-analysis limit, and usage count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sub = ctx.getUserId();
    const userId = await resolveUserId(sub);
    if (!userId) {
      return {
        content: [{ type: "text", text: "No profile found for the signed-in user." }],
        isError: true
      };
    }
    const admin = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await admin.from("user_subscriptions").select("plan, monthly_limit, usage_count, current_period, period_end").eq("user_id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No subscription found for this user." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var auth0Domain = "dev-2uqchs17am41r5ed.us.auth0.com";
var auth0Audience = define_import_meta_env_default.VITE_AUTH0_AUDIENCE ?? "1cFscmFCBSd9mSliVUSCqi1EfQqJhHkt" ?? "auth0-audience-unset";
var mcp_default = defineMcp({
  name: "photo-organizer-mcp",
  title: "Photo Organizer MCP",
  version: "0.1.0",
  instructions: "Tools for this photo organizer app. Use `echo` to verify connectivity and `get_my_usage` to read the signed-in user's plan and monthly image-analysis usage.",
  auth: auth.oauth.issuer({
    issuer: `https://${auth0Domain}/`,
    acceptedAudiences: auth0Audience
  }),
  tools: [echo_default, get_my_usage_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
