// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhejjpqngvlttrdpgofr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWpqcHFuZ3ZsdHRyZHBnb2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODYxNDEsImV4cCI6MjA3MDY2MjE0MX0.G0lr22FeyMB2e2nYbLCYxluBzDbdW19sthdzjXw0ZoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});